### ISSUE TITLE
Return 400 instead of 500/404?

### ISSUE THREAD

**Issue by mmoravcik** [anx-ckreuzberger/django-rest-passwordreset#12]
Any reason why the app return 500/404 error instead of 400 in these, and perhaps other, cases?

* non-existent email address has been provided
* token is invalid (expired, deleted, mistyped)

I think that catching 400 and getting the errors from the response would be much neater to work with in FE?

**Comment by anx-ckreuzberger** [comment]
I've created issue #19 for this and closing this one.

**Comment by anx-ckreuzberger** [comment]
Changes for this have just released in [Version 1.0.0a1](https://pypi.org/project/django-rest-passwordreset/1.0.0a1/).
