### ISSUE TITLE
cannot import name 'message_from_file'

### ISSUE THREAD

**Issue by giovannicimolin** [anx-ckreuzberger/django-rest-passwordreset#13]
When I try adding `'django_rest_passwordreset'` to django apps, I get this error:
```
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    from django.core.management import execute_from_command_line
  File "/home/giovanni/git/ozzy-backend/venv/lib/python3.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/home/giovanni/git/ozzy-backend/venv/lib/python3.6/site-packages/django/utils/version.py", line 6, in <module>
    from distutils.version import LooseVersion
  File "/home/giovanni/git/ozzy-backend/venv/lib/python3.6/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
  File "/usr/lib64/python3.6/distutils/dist.py", line 10, in <module>
    from email import message_from_file
ImportError: cannot import name 'message_from_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
And removing it my app runs fine. Can you help me with this issue?
This has something to do with the `email` package?

**Django:** 2.1.2
**Python:** 3.6
Using virtualenv.

**Comment by anx-ckreuzberger** [comment]
Hi!

This issue seems to be coming from your virtualenv and/or package manager itself, not from django-rest-passwordreset.

Are you using virtualenv or pipenv? Is this happening with the latest version of django-rest-passwordreset (0.9.6) or also with older versions (e.g., 0.9.5)?

How are you installing the package? (using `pip install django-rest-passwordreset`?)

**Comment by giovannicimolin** [comment]
Hi!

I'm creating the virtualenv like this `virtualenv venv -p python36`.
To use the virtualenv, I either use **direnv** with a `.envrc` file containing 
```
source venv/bin/activate
```
I've installed the package using `pip install django-rest-passwordreset`.

**pip Version: 10.0.01**
I'm using Django 2.1.2.
I can't do a `pip freeze` right now because I'm traveling.
Weird thing is when I remove `django-rest-passwordreset` from my project it works fine.

Maybe it's a problem with my e-mail backend configuration?
```
# E-mail settings
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = credentials.EMAIL_DEFAULT_FROM
SERVER_EMAIL = credentials.EMAIL_SERVER
EMAIL_HOST = credentials.EMAIL_HOST
EMAIL_PORT = credentials.EMAIL_PORT
EMAIL_HOST_USER = credentials.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = credentials.EMAIL_HOST_PASSWORD
```

**Comment by giovannicimolin** [comment]
Some dependency on `django-rest-passwordreset` breaks Python on my entire system.

I'm using Arch Linux with Python 3.7 on system and Python 3.6 on the virtualenv, when I run `pip install django-rest-passwordreset` something happens all Python installs I have break. 

I've tried on 2 computers and reinstalled my system and the problem still happens (guess who going to reinstall his system again :cry:).

**Comment by anx-ckreuzberger** [comment]
This should really not be the case at all. In addition, a package that you install in a virtualenv should not (and actually can not) break your system python installation (if it does, then something else is really wrong with your virtualenv or python installation...).

We're using this library heavily on debian and Ubuntu systems, and have never had an issue like this before. 
Also, the library itself does not install any dependencies etc...,  nor does it have any requirements on other libraries (obviously, it is expected that you have django and django rest framework installed).

Is it possible that your virtualenv version is quite old? Can you do a
```bash
virtualenv --version
```

and if possible upgrade virtualenv on your system before you install the project and dependencies?
Also, if you are using a virtualenv anywhere on your system make sure to re-generate the whole virtualenv before you continue.

**Comment by giovannicimolin** [comment]
I get this error using `virtualenv`, `pyenv` and even with a isolated Python install, but it only happens after I run:

**Comment by giovannicimolin** [comment]
Doesn't seem to be exactly a problem on your lib, but triggered from it.

**Comment by anx-ckreuzberger** [comment]
Hi! I'm wondering if you came across this issue again (or if you found a solution to it, other than not using this package)?

**Comment by saurabhaec** [comment]
I am also getting same msg with import pandas as pd  in django web application

**Comment by anx-ckreuzberger** [comment]
@giovannicimolin @saurabhaec Do you happen to have a file called "email.py" (or a folder called "email") somewhere within your project?

**Comment by rinshankolayil** [comment]
I got this problem, I have tried to run sever through virtual env
django runserver 0.0.0.0:8000
this seems to be working
when I am trying with apache (by http:80) it was not working. I think it seems to error from import library from site_packages. Try on checking python path given in apache2 configuration because it works with django runserver method.

**Comment by anx-ckreuzberger** [comment]
@rinshankolayil do you happen to have a file called "email.py" or a folder called "email" somewhere within your project?

**Comment by rinshankolayil** [comment]
@anx-ckreuzberger : Aah may be there is one. I will check and tell you.Anyway thanks
