### ISSUE TITLE
How can i post email id for password reset ?

### ISSUE THREAD

**Issue by Suryanandsingh** [anx-ckreuzberger/django-rest-passwordreset#15]
When I am putting this urls into my browser:-

      from django.conf.urls import url, include
       urlpatterns = [
        ...
         url(r'^api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
       ...
      ]
then I am getting **"Method \"GET\" not allowed."** there is nothing to show where i put email.

**Comment by anx-ckreuzberger** [comment]
It's not intended to be used with the browsable API (though this is something we can work out, if anyone wants to do that).

You can not use a "GET" request for that either, it needs to be a POST request.

See https://github.com/anx-ckreuzberger/django-rest-passwordreset#endpoints for more details.

**Comment by anx-ckreuzberger** [comment]
I've created issue #19 for this and closing this one.
