### ISSUE TITLE
Clear expired tokens command

### ISSUE THREAD

**Issue by iagocanalejas** [anx-ckreuzberger/django-rest-passwordreset#17]
Add a command to remove all expired tokens from the database. This could be a performance and size problem in large databases. I sugest somthing like [django-oauth-toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/management_commands.html) implementation

**Comment by anx-ckreuzberger** [comment]
It shouldn't become a performance issue, unless somebody is forcefully abusing the system.

We are auto-deleting all tokens that are too old here:
https://github.com/anx-ckreuzberger/django-rest-passwordreset/blob/master/django_rest_passwordreset/views.py#L99

I will however document that behaviour, and create a management command for it (as this is really a no-brainer).

**Comment by anx-ckreuzberger** [comment]
You're welcome :) If not, I'll do it myself tonight.

**Comment by anx-ckreuzberger** [comment]
Changes for this have just released in [Version 1.0.0a1](https://pypi.org/project/django-rest-passwordreset/1.0.0a1/).
