### ISSUE TITLE
DRF browsable API is not working

### ISSUE THREAD

**Issue by aryabartar** [anx-ckreuzberger/django-rest-passwordreset#26]
When I go to reset-password endpoint DRF browsable API is not working (package doc mentioned that browsable API support is available).

```
urlpatterns = [
    path('password-reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
]
```
Is there any settings that I have to change?

**Comment by anx-ckreuzberger** [comment]
With the latest version ``1.0.0a1`` this should be working out of the box.

I don't think that you need to do anything special to enable it. Just make sure that you have a BrowsableAPIRenderer in your settings.py, e.g.:
```python
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_xml.renderers.XMLRenderer',
    ),
}
```
