### ISSUE TITLE
Django IntegrityError: Column 'is_superuser' cannot be null

### ISSUE THREAD

**Issue by blackadress** [anx-ckreuzberger/django-rest-passwordreset#30]
Using Django 2.1.5 here and this library's 1.0.0a3 version, when sending token and password from a user with no admin privileges ('is_superuser' = False) to the endpoint, I get this error on line 74 on the views.py file
`
reset_password_token.user.save()
`

It is because Django, in my specific case, when returning user from the DB and a BooleanField is False it returns with 'null' as value (i really don't understand how or why).

A quick hack to solve this is to put an ugly if else to check if user.is_superuser, user.is_staff are null, if they are, then assign False to them:
`if reset_password_token.user.is_superuser is None:`
    `reset_password_token.user.is_superuser = False`
`if reset_password_token.user.is_staff is None:`
    `reset_password_token.user.is_staff = False`

Can someone give me other options or explain me how is it that django query gives me null instead of False

**Comment by anx-ckreuzberger** [comment]
very interesting :confused: 

A few questions:
* Does this only happen with 1.0.0a3 or also with 0.9.7?
* Which database and Django Database Backend are you using?

I wouldn't want to include that very specific fix into the code (literally any boolean field will cause that issue, not just `is_superuser`), but what I could do is to adapt this code:
https://github.com/anx-ckreuzberger/django-rest-passwordreset/blob/e7e61fbab249b1155614aa340dff9a20a45f386f/django_rest_passwordreset/views.py#L73-L74
to this:
```python
reset_password_token.user.set_password(password) 
reset_password_token.user.save(update_fields=['password']) 
```

**Comment by blackadress** [comment]
Long story short in 0.9.7 i had the error of "line 141 missing positional argument of instance", and as the 1.0.0a3 addresses that I just updated to be met with the issue of Django returning a 'null' instead of False, hence the extremely ugly fix. I'll probably just change the if else to save(update_fields=['password'].

My buddy right now is using the 0.9.7 with just the fix in views.py line 141 -adding instance=self to `reset_password_token.send(sender=self.__class__, reset_password_token=token)`

I didn't use de save(update_fields=['password']) because I didn't know at the time of the handy update_fields, but hey you learn something everyday :+1: 

The backend I'm currently using is mysql-connector-python==8.0.15, in the DB the False values are being saved (as 0 because tinyint) so probably the returning null is this driver's doing.

**Comment by blackadress** [comment]
Thanks for the suggestions and solutions, for now the fix in the library will be enough :).
The change for msqlclient is gonna be a 4-5gb c++ runtime or something on a slow net for the windows users in the team. Can't wait to tell them haha.

I'm closing the issue and thanks again for the answers.

**Comment by anx-ckreuzberger** [comment]
> The change for msqlclient is gonna be a 4-5gb c++ runtime or something on a slow net for the windows users in the team.
I can't deny that I have a grin in my face right now :P

I really wonder if that behaviour of the mysql native client and Django is documented, or if there is another issue somewhere in the database. But I'm happy that it works now!

**Comment by anx-ckreuzberger** [comment]
FYI, if you want to avoid the Windows binary problem, you can try to use this:
```bash
pip install --only-binary mysqlclient -r requirements.txt
```
(assuming that your requirements.txt contains all other requirements)

**Comment by squio** [comment]
> Okay, seems that `mysql-connector-python` could be the cause.
> If you don't have any reasons for that connector, I recommend using
> 
> ```
> mysqlclient>=1.3,<1.4
> ```
> 
> (make sure to uninstall mysql-connector first), and in your settings you should use the `'django.db.backends.mysql'` engine, e.g.:
> 
> ```python
> DATABASES = {
>     'default': {
>         'ENGINE': 'django.db.backends.mysql',
>         'NAME': 'database',
>         'USER': 'root',
>         'PASSWORD': 'database',
>         'HOST': 'mysql',
>         'ATOMIC_REQUESTS': True,
>     }
> ```
> 
> FYI, thi sis also what Django itself recommends: https://docs.djangoproject.com/en/2.1/ref/databases/#mysql-db-api-drivers
> 
> Alternatively, MySQL provides more information about its connector here: https://dev.mysql.com/doc/connector-python/en/connector-python-django-backend.html
> 
> If the driver is really the root cause, I highly recommend avoiding that driver (or find out if you can configure that driver differently), because you will end up having much more issues in the future.

Quick heads-up: this seems to be a drive issue indeed, elaborate bug report here:

https://code.djangoproject.com/ticket/30469
