### ISSUE TITLE
Update pipy package

### ISSUE THREAD

**Issue by othane** [anx-ckreuzberger/django-rest-passwordreset#32]
This is more a request than a bug report (sorry but I could not find a better place for it).

This looks like a great little library which will save me from having to repeat this code in my own projects, but Its been a while since the last pipy update and 0.9.7 has quite a few major issues that have now sorted out ... would it be possible to update the pipy version to one of the newest commits soon?

**Comment by anx-ckreuzberger** [comment]
It's actually released as an "alpha" release, which you can see here:
https://pypi.org/project/django-rest-passwordreset/#history
You can install 
```bash
pip install django-rest-passwordreset==1.0.0a3
```

**Comment by othane** [comment]
oh perfect :+1:  ... sorry I should have looked harder :)

**Comment by anx-ckreuzberger** [comment]
No worries - I plan to release 1.0.0 "final", just didn't have the time for it so far...
