### ISSUE TITLE
Cannot access the browsable API for the given end-points

### ISSUE THREAD

**Issue by jroeland** [anx-ckreuzberger/django-rest-passwordreset#33]
I see in the docs some screenshots of the browsable API, however when i try to access it, I get the following message:
```
Method \"GET\" not allowed
```

Also, in the generated docs, where it says `Interact` there is no form to interact with.

Where these removed?

**Comment by TorfinS** [comment]
Why did you use GET request?

**Comment by jroeland** [comment]
@TorfinS To use the browsable API, you need to navigate to the end-point using a get request. Unless i am missing something?

Use this example:

```python

# Urls
url(r"^account/password_change/", ChangePasswordView.as_view()),

# Views
class ChangePasswordView(generics.UpdateAPIView):
    """
        An endpoint for changing password.
        """

    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)
```

If i navigate to `/account/password_change/` I am able to use the browsable api even if the get method is not allowed. See screenshot.

![demoget](https://user-images.githubusercontent.com/7986681/55614637-b4647b00-578d-11e9-919e-eb2ae0f05e9e.png)

**Comment by rajath95** [comment]
You need to pass a POST request with your email as a key

**Comment by anx-ckreuzberger** [comment]
Is it the same issue as with #26?

Did you install version `1.0.0a1` or newer? (if you just do `pip install django-rest-passwordreset` without a version, you get `0.9.7` which does not support this yet.

**Comment by jroeland** [comment]
@rajath95 I shouldn't need to make a POST request to access the browsable API. See the example I have given.

@anx-abruckner That is indeed the issue, I have not noticed that. My apologies :)
