### ISSUE TITLE
How do I trigger the email signal?

### ISSUE THREAD

**Issue by rajath95** [anx-ckreuzberger/django-rest-passwordreset#35]
How do I trigger the email signals?
The api is able to verify the email but the signals are not being triggered.
How do I trigger the signals?

**Comment by anx-ckreuzberger** [comment]
Did you take a look at the example? https://github.com/anx-ckreuzberger/django-rest-passwordreset#example-for-sending-an-e-mail

Closing this as it sounds more like a support request rather than a bug.
