### ISSUE TITLE
password_reset_token_created() missing 1 required positional argument: 'instance'

### ISSUE THREAD

**Issue by rajath95** [anx-ckreuzberger/django-rest-passwordreset#36]
I was able to enter the email. However I got the following error.

TypeError at /password_reset/
password_reset_token_created() missing 1 required positional argument: 'instance'

**Comment by anx-ckreuzberger** [comment]
Hi,

which version are you using? Since 1.0.0 (alpha) we require the "instance" parameter to be set in the signal:
```python

@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
    """
    Handles password reset tokens
    When a token is created, an e-mail needs to be sent to the user
    :param sender: View Class that sent the signal
    :param instance: View Instance that sent the signal
    :param reset_password_token: Token Model Object
    :param args:
    :param kwargs:
    :return:
    """
```

You probably are using an older version (0.9.7), so just remove the `instance`parameter for now :)

**Comment by rajath95** [comment]
Thanks!
