### ISSUE TITLE
How to customize exceptions

### ISSUE THREAD

**Issue by TorfinS** [anx-ckreuzberger/django-rest-passwordreset#41]
Hi,
sorry about my question but I can not find any info about it (title) in docs. How can I extend exceptions e.g
api/password_reset/ - email not found (customize structure)
api/password_reset/confirm - invalid token (customize structure)
...
It is possible to do this? Should I use exception handler?

**Comment by TorfinS** [comment]
To his time, I tied:
```
# views.py
from django_rest_passwordreset.views import ResetPasswordRequestToken

class PasswordResetView(APIView):
    def post(self, request, format=None):
        try:
            if '@' not in request.data['email']:
                return Response({'status': 'Error', 'error': 'Invalid email address'}, status=404)
            if User.objects.filter(email=request.data['email']):
                # Draft - just tried do something
                response = ResetPasswordRequestToken(request)
                return Response(response)
            else:
                return Response({'status': 'Error', 'error': 'Email not found'}, status=404)
        except:
            return Response({'status': 'Error', 'error': 'Invalid data - fileds required: email'}, status=404)
```
How to correctly use dependency views without urls?

**Comment by anx-ckreuzberger** [comment]
The exceptions are thrown in various ways:

* By the serializer (e.g., invalid token or invalid e-mail)
    ```python
    serializer.is_valid(raise_exception=True)
    ```
* By manually raising a `exceptions.ValidationError`:
    ```python
    raise exceptions.ValidationError({
        'password': e.messages
    })
    ```
* Sometimes we just return a 404 Not Found:  ``return Response({'status': 'notfound'}, status=status.HTTP_404_NOT_FOUND)``

If you want to customize those exceptions or the handling of them, you need to overwrite the ``ResetPasswordConfirm`` class and/or the ``ResetPasswordRequestToken`` class with your own class, create a new "function view"
```python
reset_password_confirm = ResetPasswordConfirm.as_view()
reset_password_request_token = ResetPasswordRequestToken.as_view()
```
and include those in your `urls.py`.

**Comment by TorfinS** [comment]
Works!
