### ISSUE TITLE
Historic of requested password resets

### ISSUE THREAD

**Issue by iagocanalejas** [anx-ckreuzberger/django-rest-passwordreset#42]
Hi, after some thinking of the use i personally do of this library i think allowing `ResetPasswordToken` soft-deletion (maybe in some configuration param) could be a nice addition to the library current features.

Allowing this you can use `ip_address` (already being saved) to detect account attacks (as an example). But at less you can have a historic of user reset requests.

**Comment by anx-ckreuzberger** [comment]
Improving security is always a good idea. 

One could accomplish this right now by using a Django `post_save` receiver, and storing details of the IP address in another table.

Though I wouldn't want to re-purpose the `ResetPasswordToken` table/model for this behaviour, as I believe in the philosophy of "do one thing and do it very well". In addition, I guess that many services must comply with the EUs GPDR, therefore storing the reset information (ip address, user agent, ...) while "the information is needed" for the password reset is okay, but archiving it could lead to issues. 

Anyway, are there any Django packages out there that could be used to track the IP address of users (for later analysis)? Do we need to adapt this package to make them compatible (e.g., sending signals, configuration options, etc...)?

**Comment by iagocanalejas** [comment]
Makes sense, thank you for the complete answer
