### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by wencakisa** [anx-ckreuzberger/django-rest-passwordreset#50]
I've noticed a minor, but common typo in the word `length` [in the section with examples of overriding `DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG`](https://github.com/anx-ckreuzberger/django-rest-passwordreset#randomstringtokengenerator):

> You can configure the length as follows:
> ```py
> 
> DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG = {
>     "CLASS": "django_rest_passwordreset.tokens.RandomStringTokenGenerator",
>     "OPTIONS": {
>         "min_length": 20,
>         "max_lenght": 30
>        # ________^
>     }
> }
> 
> ```

It is mistyped as **`lenght`** instead of **`length`**.

**Comment by anx-ckreuzberger** [comment]
*facepalm*

Thank you, I'll try to fix this asap (alternatively PR welcome :D)

**Comment by wencakisa** [comment]
@anx-abruckner I'll submit a PR in a moment. :)

**Comment by anx-ckreuzberger** [comment]
Thank you!
