### ISSUE TITLE
Migration Error at /api/password_reset/

### ISSUE THREAD

**Issue by ambaresthete** [anx-ckreuzberger/django-rest-passwordreset#56]
Migration Error at /api/password_rest/
id 
Django version = 2.0.6
Python  = 3.6
django rest framework = 3.8.2

The error occurs after submitting the post request with email. I am using djongo library. MongoDB as database. Is it the problem with database or version dependencies

**Comment by anx-ckreuzberger** [comment]
Is this related to #57 ? Did you run `python manage.py migrate`?

**Comment by ambaresthete** [comment]
No it's not related to #57, I checked all the issues nothing related. Yes i
did run migrate command.

**Comment by anx-ckreuzberger** [comment]
As detailed in Issue #49 there are some problems with MongoDB. Please take a look at the last comment in this issue.

**Comment by ambaresthete** [comment]
That solves the problem. Thank you very much.

**Comment by anx-ckreuzberger** [comment]
Good to hear. I'm not very familiar with MongoDB (especially not for Django Models), so I'm curious whether AutoField is just not possible and that "fix" described in #49 is the way to go?
