### ISSUE TITLE
Setting min_length and max_length does not work

### ISSUE THREAD

**Issue by SamNgu** [anx-ckreuzberger/django-rest-passwordreset#62]
I have set this inside my settings file, but it does not seem to work at all.

DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG = {
    "CLASS": "django_rest_passwordreset.tokens.RandomStringTokenGenerator",
    "OPTIONS": {
        "min_number": 10,
        "max_number": 100
    }
}

**Comment by anx-ckreuzberger** [comment]
This is only available since version 1.1, which is currently available as a release candidate.
See https://pypi.org/project/django-rest-passwordreset/#history

You can install it using ``pip install django-rest-passwordreset==1.1.0rc3``

**Comment by SamNgu** [comment]
ah, I see, no wonder. Thanks!
